#! /usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
# Copyright 2014, 2017, 2022 Peter Williams
# Licensed under the MIT License.

"""Read the dictionary into a Bloom filter and save the filter state for quick
loading later.

"""
import gzip

try:
    import cPickle as pickle
except ImportError:
    import pickle

import bloom


# This stuff is specific to Peter's machine: the dictionary contains about
# 479000 words and lives in the standard Unixy location.

bf = bloom.optimal_bloom(0.05, 479000)

for line in open("/usr/share/dict/words"):
    bf.add(line.strip())

pickle.dump(bf, gzip.GzipFile("dictbf.dat.gz", "wb", 9))
